name: Build

on:
  workflow_call:
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build.yml"
      - ".githooks/**"
      - "LICENSE"
      - "README.md"

jobs:
  gitversion:
    uses: tiobe/workflows/.github/workflows/gitversion.yml@v0
  build:
    runs-on: ubuntu-latest
    needs: gitversion
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
      - name: Build all
        run: ./scripts/build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: htmltox
          path: |
            build/htmltox.exe
            build/htmltox-linux-amd64
            build/htmltox-linux-arm64
            build/htmltox-darwin-amd64
            build/htmltox-darwin-arm64
