name: Build

on:
  workflow_call:
  push:
    branches: '*'
    tags-ignore: '*'
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build.yml"
      - ".githooks/**"
      - "LICENSE"
      - "README.md"

jobs:
  gitversion:
    uses: ./.github/workflows/gitversion.yml
  build:
    runs-on: ubuntu-latest
    needs: gitversion
    outputs:
      version: ${{needs.gitversion.outputs.fullSemVer}}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
      - name: Build all
        run: ./scripts/build.sh
        env:
          VERSION: ${{ needs.gitversion.outputs.fullSemVer }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: htmltox
          path: |
            build/htmltox.exe
            build/htmltox-linux-amd64
            build/htmltox-linux-arm64
            build/htmltox-darwin-amd64
            build/htmltox-darwin-arm64
