name: GitVersion

on:
  workflow_call:
    outputs:
      fullSemVer:
        value: ${{jobs.gitversion.outputs.fullSemVer}}
      assemblySemFileVer:
        value: ${{jobs.gitversion.outputs.assemblySemFileVer}}

jobs:
  gitversion:
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{steps.gitversion.outputs.fullSemVer}}
      assemblySemFileVer: ${{steps.gitversion.outputs.assemblySemFileVer}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Create GitVersion.yml
        shell: bash
        run: |
          cat > GitVersion.yml << EOF
          increment: None
          branches:
            main:
              increment: None
          EOF
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.2.0
        with:
          versionSpec: "6.3.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.2.0
